# Generated by Django 3.0.3 on 2020-05-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='user',
        ),
        migrations.AddField(
            model_name='audit',
            name='name',
            field=models.CharField(default='ABCXYZ', max_length=264),
        ),
    ]
