# Generated by Django 3.0.3 on 2020-05-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200501_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='created',
        ),
        migrations.AddField(
            model_name='audit',
            name='login_time',
            field=models.CharField(default='2020-05-01 12:02:07.201537', max_length=264),
        ),
        migrations.AddField(
            model_name='audit',
            name='logout_time',
            field=models.CharField(default='2020-05-01 12:02:07.201537', max_length=264),
        ),
    ]
